---
ci:
  autofix_commit_msg: "fix: resolve commit violations"
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_commit_msg: "ci: update pre-commit hooks"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--config-file, .github/yamllint.yaml, --format, github, --strict]
